### ISSUE TITLE
Handle acknowledgements and timeouts in `ics20.qnt`

### ISSUE THREAD

**Issue by bugarela** [informalsystems/apalache-team-services#8]
```[tasklist]
### Tasks
- [x] Add synchronous acknowledgements (https://github.com/informalsystems/quint/pull/858)
- [x] Make acknowledgements asynchronous (https://github.com/informalsystems/quint/pull/858)
- [x] Add an acknowledgement test (https://github.com/informalsystems/quint/pull/858)
- [ ] Add timeouts (https://github.com/informalsystems/quint/pull/865)
- [ ] Add a timeout test (https://github.com/informalsystems/quint/pull/865)
```
